name: Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup volta
        uses: volta-cli/action@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Generate code coverage
        run: pnpm test

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
